version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      - DJANGO_SUPERUSER_USERNAME=ranafathimaadmin
      - DJANGO_SUPERUSER_EMAIL=admin@gmail.com
      - DJANGO_SUPERUSER_PASSWORD=ranafathima123
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  postgres_data:
