# Generated by Django 6.0.4 on 2026-05-02 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cart_created_at_alter_cart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
